### PR TITLE
Time fix

### PR DESCRIPTION
**Pull request by Dr-Danimal**
Fixed time continuity by passing a start time to `SplineGenerator::parameterize`.

### CODE REVIEW

**Comment by Dr-Danimal** [comment]
@baylessj

**Comment by baylessj** [comment]
Hi @Dr-Danimal, thanks for opening this! I have a couple of fixes for the tests that I'd like to add but I don't have write access. Could you please check the box on this PR to allow contributions by maintainers?

**Comment by Dr-Danimal** [comment]
@baylessj The "Allow edits by maintainers" is checked, Is there somewhere else I need to give access?

**Comment by baylessj** [comment]
Github needed me to clone the repo first to push to your branch for some reason, I couldn't just add it as a remote. All good now

**Pull request merged**
